from audioop import reverse

print('Analizador de texto')
print("Analisis 1")
texto = input('Ingresa un texto: ').lower()
letra1 = input('Ingresa la primera letra: ').lower()
letra2 = input('Ingresa la segunda letra: ').lower()
letra3 = input('Ingresa la tercera letra: ').lower()
list(letra1)
list(letra3)
list(letra2)
conteo1 = texto.count(letra1)
conteo2 = texto.count(letra2)
conteo3 = texto.count(letra3)
print(f"La letra '{letra1}' aparece {conteo1} veces")
print(f"La letra '{letra2}' aparece {conteo2} veces")
print(f"La letra '{letra3}' aparece {conteo3} veces")
print("<--------------------------->")
print("Analisis 2")
palabras = texto.split()
largo = len(palabras)
print(f"Tu texto tiene un total de {largo} palabras")
print("<--------------------------->")
print("Analisis 3")
indice = texto[0]
indice2 = texto[-1]
print(f"La primera letra de tu texto es: {indice} y la segunda es: {indice2}")
print("<--------------------------->")
print("Analisis 4")
palabras.reverse()
union = " ".join(palabras)
print(union)
print("<--------------------------->")
print("Analisis 5")
print("Python" in texto)
